static const struct {
    const char *htmlentity;
    const char *charstring;
} htmlentity_to_charstrings[] = {
    // Control Characters 0-31
    // Special Characters and Numbers 32-63
    {"&sp;", " "},
    {"&excl;", "!"},
    {"&quot;", "\""},
    {"&num;", "#"},
    {"&dollar;", "$"},
    {"&percnt;", "%"},
    {"&amp;", "&"},
    {"&apos;", "'"},
    {"&lpar;", "("},
    {"&rpar;", ")"},
    {"&ast;", "*"},
    {"&plus;", "+"},
    {"&comma;", ","},
    {"&minus;", "-"},
    {"&period;", "."},
    {"&sol;", "/"},
    {"&colon;", ":"},
    {"&semi;", ";"},
    {"&lt;", "<"},
    {"&equals;", "="},
    {"&gt;", ">"},
    {"&quest;", "?"},
    // Upper Case Letters 64-95
    {"&commat;", "@"},
    {"&lsqp;", "["},
    {"&bsol;", "\""},
    {"&rsqp;", "]"},
    {"&circ;", "^"},
    {"&lowbar;", "_"},
    {"&horbar;", "_"},
    // Lower Case Letters 96-127
    {"&grave;", "`"},
    {"&lcub;", "{"},
    {"&verbar;", "|"},
    {"&rcub;", "}"},
    {"&tilde;", "~"},
    // Extended Control Characters 128-159
    // Special Characters 160-191
    {"&nbsp;", " "},
    {"&iexcl;", "¡"},
    {"&cent;", ""},
    {"&pound;", "£"},
    {"&curren;", "¤"},
    {"&yen;", "¥"},
    {"&brkbar;", "¦"},
    {"&brvbar;", "¦"},
    {"&sect;", ""},
    {"&uml;", ""},
    {"&die;", ""},
    {"&copy;", ""},
    {"&ordf;", ""},
    {"&laquo;", "«"},
    {"&not;", "¬"},
    {"&shy;", ""},
    {"&reg;", "®"},
    {"&macr;", "¯"},
    {"&hibar;", "¯"},
    {"&deq;", "°"},
    {"&plusmn;", "±"},
    {"&sup2;", "²"},
    {"&sup3;", "³"},
    {"&acute;", "´"},
    {"&micro;", "µ"},
    {"&para;", "¶"},
    {"&middot;", "·"},
    {"&cdeil;", "¸"},
    {"&sup1;", "¹"},
    {"&ordm;", "º"},
    {"&raquo;", "»"},
    {"&frac14;", "¼"},
    {"&frac12;", "½"},
    {"&half;", "½"},
    {"&frac34;", "¾"},
    {"&iquest;", "¿"},
    // Upper Case Latin-1 Letters 192-223
    {"&Agrave;", "À"},
    {"&Aacute;", "Á"},
    {"&Acirc;", "Â"},
    {"&Atilde;", "Ã"},
    {"&Auml;", "Ä"},
    {"&Aring;", "Å"},
    {"&AElig;", "Æ"},
    {"&Ccedil;", "Ç"},
    {"&Egrave;", "È"},
    {"&Eacute;", "É"},
    {"&Ecirc;", "Ê"},
    {"&Euml;", "Ë"},
    {"&Igrave;", "Ì"},
    {"&Iacute;", "Í"},
    {"&Icirc;", "Î"},
    {"&Iuml;", "Ï"},
    {"&ETH;", "Ð"},
    {"&Ntilde;", "Ñ"},
    {"&Ograve;", "Ò"},
    {"&Oacute;", "Ó"},
    {"&Ocirc;", "Ô"},
    {"&Otilde;", "Õ"},
    {"&Ouml;", "Ö"},
    {"&times;", "×"},
    {"&Oslash;", "Ø"},
    {"&Ugrave;", "Ù"},
    {"&Uacute;", "Ú"},
    {"&Ucirc;", ""},
    {"&Uuml;", "Ü"},
    {"&Yacute;", ""},
    {"&THORN;", "Þ"},
    {"&szlig;", "ß"},
    // Lower Case Latin-1 Letters 224-255
    {"&agrave;", "à"},
    {"&aacute;", "á"},
    {"&acirc;", ""},
    {"&atilde;", "ã"},
    {"&auml;", "ä"},
    {"&aring;", ""},
    {"&aelig;", "æ"},
    {"&ccedil;", "ç"},
    {"&egrave;", "è"},
    {"&eacute;", "é"},
    {"&ecirc;", "ê"},
    {"&euml;", "ë"},
    {"&igrave;", "ì"},
    {"&iacute;", "í"},
    {"&icirc;", ""},
    {"&iuml;", "ï"},
    {"&eth;", ""},
    {"&ntilde;", "ñ"},
    {"&ograve;", "ò"},
    {"&oacute;", "ó"},
    {"&ocirc;", "ô"},
    {"&otilde;", "õ"},
    {"&ouml;", "ö"},
    {"&divide;", "÷"},
    {"&oslash;", "ø"},
    {"&ugrave;", "ù"},
    {"&uacute;", "ú"},
    {"&ucirc;", ""},
    {"&uuml;", "ü"},
    {"&yacute;", ""},
    {"&thorn;", "þ"},
    {"&yuml;", "ÿ"}
};
