#!/bin/sh

file=$1
extension=$(echo $file | awk '{n=split($0,a,"."); print a[n]}')

if [ "$extension" = "pdf" ]; then
    zathura "$file" &
elif [ "$extension" = "mscz" ]; then
    musescore "$file" &
elif [ "$extension" = "png" ] || [ "$extension" = "JPG" ] || [ "$extension" = "jpg" ] || [ "$extension" = "jpeg" ] || [ "$extension" = "ppm" ] || [ "$extension" = "pgm" ]; then
    feh "$file" &
elif [ "$extension" = "mp3" ] || [ "$extension" = "VOB" ]; then
    vlc "$file" &
elif [ "$extension" = "mp4" ] || [ "$extension" = "m4v" ] || [ "$extension" = "avi" ] || [ "$extension" = "flv" ] || [ "$extension" = "mpg" ] || [ "$extension" = "mkv" ]; then
    mpv "$file" &
elif [ "$extension" = "odt" ] || [ "$extension" = "ods" ] || [ "$extension" = "odp" ] || [ "$extension" = "docx" ] || [ "$extension" = "xlsx" ] || [ "$extension" = "pptx" ]; then
    libreoffice --norestore "$file" &
elif [ -d $file  ]; then
    cd "$file"
    zsh
else
    $EDITOR "$file"
fi
