all:
	cd nohtml && make
	cd cptt && make
	cd xib && make
	cd xifi && make
	cd wttcp && make
	cd xns && make

install:
	cd nohtml && make install
	cd cptt && make install
	cd xib && make install
	cd xifi && make install
	cd wttcp && make install
	cd xns && make install

clean:
	cd nohtml && make clean
	cd cptt && make clean
	cd xib && make clean
	cd xifi && make clean
	cd wttcp && make clean
	cd xns && make clean
