all:
	cd nohtml && make
	cd cptt && make
	cd xib && make
	cd xifi && make
	cd wttcp && make
	cd xns && make
	cd tts && make
	cd ttc && make
	cd uts && make
	cd utc && make

install:
	cd nohtml && make install || echo "could not install"
	cd cptt && make install || echo "could not install"
	cd xib && make install || echo "could not install"
	cd xifi && make install || echo "could not install"
	cd wttcp && make install || echo "could not install"
	cd xns && make install || echo "could not install"
	cd tts && make install || echo "could not install"
	cd ttc && make install || echo "could not install"
	cd uts && make install || echo "could not install"
	cd utc && make install || echo "could not install"

clean:
	cd nohtml && make clean
	cd cptt && make clean
	cd xib && make clean
	cd xifi && make clean
	cd wttcp && make clean
	cd xns && make clean
	cd tts && make clean
	cd ttc && make clean
	cd uts && make clean
	cd utc && make clean
