all:
	cd nohtml && make
	cd cptt && make
	cd xib && make
	cd xifi && make
	cd wttcp && make
	cd xns && make
	cd tts && make
	cd ttc && make
	cd uts && make
	cd utc && make

install:
	cd nohtml && make install
	cd cptt && make install
	cd xib && make install
	cd xifi && make install
	cd wttcp && make install
	cd xns && make install
	cd tts && make install
	cd ttc && make install
	cd uts && make install
	cd utc && make install

clean:
	cd nohtml && make clean
	cd cptt && make clean
	cd xib && make clean
	cd xifi && make clean
	cd wttcp && make clean
	cd xns && make clean
	cd tts && make clean
	cd ttc && make clean
	cd uts && make clean
	cd utc && make clean
